### ISSUE TITLE
A problem occurred configuring project ':react-native-community_masked-view'.

### ISSUE THREAD

**Issue by hossein-zare** [react-native-masked-view/masked-view#48]
# Bug

After installing '@react-native-community/masked-view' i'm facing this error.
I also installed a bunch of gradle versions and plugins but still the same.

## Environment info

  Binaries:
    Node: 10.13.0
    Yarn: 1.17.3
    npm: 6.4.1
  IDEs:
    Android Studio: Version  3.1.0.0 AI-173.4907809
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

React native info output:

```bash
$ npm run android

> Wester@0.0.1 android E:\Projects\ReactNative\Real\Wester
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 964 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...
<-------------> 0% WAITING
> IDLE

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-community_masked-view'.
> Could not resolve all artifacts for configuration ':react-native-community_masked-view:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.1/shared-26.3.1.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.1/crash-26.3.1.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.1/lint-gradle-api-26.3.1.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.1/gradle-api-3.3.1.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.1/databinding-compiler-common-3.3.1.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.1/manifest-merger-26.3.1.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.1/sdk-common-26.3.1.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.1/builder-test-api-3.3.1.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.1/sdklib-26.3.1.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.1/layoutlib-api-26.3.1.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.jar
   > Could not find repository.jar (com.android.tools:repository:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.1/repository-26.3.1.jar
   > Could not find common.jar (com.android.tools:common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.1/common-26.3.1.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta02/jetifier-processor-1.0.0-beta02.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta02/jetifier-core-1.0.0-beta02.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.1/builder-model-3.3.1.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.1/protos-26.3.1.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.1/apkzlib-3.3.1.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.1/apksig-3.3.1.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.1/annotations-26.3.1.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.1/databinding-common-3.3.1.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.1/baseLibrary-3.3.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-community_masked-view'.
> Could not resolve all artifacts for configuration ':react-native-community_masked-view:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/builder-3.3.1.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.3.1/tracker-26.3.1.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.3.1/shared-26.3.1.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.3.1/crash-26.3.1.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.3.1/lint-gradle-api-26.3.1.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.3.1/gradle-api-3.3.1.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.3.1/databinding-compiler-common-3.3.1.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.1/manifest-merger-26.3.1.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.3.1/sdk-common-26.3.1.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.3.1/builder-test-api-3.3.1.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.3.1/ddmlib-26.3.1.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.1/sdklib-26.3.1.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.3.1/layoutlib-api-26.3.1.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.jar
   > Could not find repository.jar (com.android.tools:repository:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.3.1/repository-26.3.1.jar
   > Could not find common.jar (com.android.tools:common:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.3.1/common-26.3.1.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta02/jetifier-processor-1.0.0-beta02.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.6.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta02).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta02/jetifier-core-1.0.0-beta02.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.3.1/builder-model-3.3.1.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.1/protos-26.3.1.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.3.1/apkzlib-3.3.1.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.3.1/apksig-3.3.1.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.3.1/annotations-26.3.1.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.3.1/databinding-common-3.3.1.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.3.1/baseLibrary-3.3.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:13)
    at runOnAllDevices (E:\Projects\ReactNative\Real\Wester\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (E:\Projects\ReactNative\Real\Wester\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
    at then.result (E:\Projects\ReactNative\Real\Wester\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Version:
"@react-native-community/masked-view": "^0.1.6"

**Comment by hamedABS** [comment]
@hossein-zare 
hey, same problem, 
did you find out the solution??

**Comment by mostafa8722** [comment]
i think you should change your gradle version

**Comment by hossein-zare** [comment]
I fixed the issue days ago but forgot it unfortunately.
I changed the Gradle to 5.6.4 and deleted the build directory.
By the way this maybe caused by the US Sanction as it doesn't let us download the requirements from the source directly. Keep in mind that anytime you're trying to update the dependencies have your VPN on.

**Comment by Lypzis** [comment]
I think I'm facing the same problem: 
> A problem occurred configuring project ':@react-native-community/masked-view'.
> The project name '@react-native-community/masked-view' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.6.4/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

**Comment by nikbakhtenb4** [comment]
I have solved this by reinstalling / updating these packages.
npm install --save react-native-gesture-handler react-native-reanimated react-native-screens

**Comment by Lypzis** [comment]
Ok, so after a lot of pain and testing, I did the following:
- Before ejecting from expo(like in my case), make sure all of your dependencies are the latest version,
if you use yarn, just run: `yarn upgrade --latest`
- Make sure the app still runs normally after this.
- Eject. 
There won't be any problems after that.

**Comment by Lypzis** [comment]
> Ok, so after a lot of pain and testing, I did the following:
> 
>     * Before ejecting from expo(like in my case), make sure all of your dependencies are the latest version,
>       if you use yarn, just run: `yarn upgrade --latest`
> 
>     * Make sure the app still runs normally after this.
> 
>     * Eject.
>       There won't be any problems after that.

Also update your app.json to the same major version installed, something like: `
"expo": {
...
    "sdkVersion": "36.0.0",
...
}
`

**Comment by msayadiyan** [comment]
hi,
I was not able to resolve my issue with above solution.
Do anyone have another solution to help me?

**Comment by msayadiyan** [comment]
> 
> 
> hi,
> I was not able to resolve my issue with above solution.
> Do anyone have another solution to help me?

I could solve it :
1- I change my VPN port and server
2- check all link to download gradle 3.3.1 manually
3- run npm install --save-dev jetifier (it is necessary to open node window for react native > 0.60.0)
4- run npm react-native run-android -----> it's OK

**Comment by amirdana** [comment]
because of US sanctions packages and requirements can't get installed correctly, make sure you're using some sort of proxy or vpn

**Comment by kunal-j10** [comment]
the **Build revision tool** you would be using might not be compatible with the version of @react-native-community_masked-view , you might be using.
So, if you want to install react-navigation^4.x, then install the navigation dependencies including @react-native-community_masked-view, and make sure that here, you use the Build revision tool version 29.0.3, as others might be incompatible with it.
